name: matrix-example

on: push



jobs:
  build:
    continue-on-error: true
    strategy:
      matrix:
        node-version: [12,14,16,18]
        operating-system: [ubuntu-latest, windows-latest]
        include:
          - node-version: 18
            operating-system: ubuntu-latest
    
    runs-on: ${{ matrix.operating-system }}
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: install node
        uses: actions/setup-node@v3
        with: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm ci
      - name: Build project
        run: npm run build

